### ISSUE TITLE
[8] ErrorException in AccessToken.php line 72  报错 未定义数组索引: code

### ISSUE THREAD

**Issue by cys138138** [justmd5/pinduoduo-sdk#1]
$config = [
            'client_id' => 'xxx',
            'client_secret' => 'xxxx',
            'debug' => true,
            'member_type' => 'MERCHANT', //用户角色 ：MERCHANT(商家授权),H5(移动端),多多客(JINBAO),
            'redirect_uri' => 'http://text.dev/index.php/pdd/index/test.html',
            'log' => [
                'name' => 'pinduoduo',
                'file' => APP_ROOT_PATH . '/runtime/log/pinduoduo.log',
                'level' => 'debug',
                'permission' => 0777,
            ],
        ];
        $this->oPdd = new PinDuoDuo($config);

 $result = $this->oPdd->auth_api->request('pdd.order.list.get', [
            'order_status' => 1,
            'refund_status' => 5,
            'page' => 1,
            'page_size' => 100,
            'start_confirm_at' => strtotime(date('Y-m-d 00:00:00')),
            'end_confirm_at' => strtotime(date('Y-m-d 23:59:59')),
        ]);
        print_r($result);

**Comment by cys138138** [comment]
调用需要授权的方法都会报错

**Comment by cys138138** [comment]
不熟悉 Foundation 流程 这个问题的原因是因为code没有设置进去 getTokenFromServer 中的$this->code 没找到复制的地方

**Comment by justmd5** [comment]
你少步骤的没发现么
调用需授权接口示例
获取授权 URL
$url = $pinduoduo->pre_auth->authorizationUrl();
重定向到授权页面
    $pinduoduo->pre_auth->authorizationRedirect();
在重定向页面，你可以获取此次授权账号的 token
$token = $pinduoduo->pre_auth->getAccessToken();
//也可以通过上面得到的 refresh_token 去刷新令牌
//$token = $pinduoduo->pre_auth->refreshToken($token['refresh_token']);

**Comment by justmd5** [comment]
你请求的'pdd.order.list.get 非授权接口（不需要code），使用api->request这样就可以了，auth_api的使用你看下readme，必须先获取授权的

**Comment by cys138138** [comment]
已经调用过的了。忘记贴出来。第一步就是调用 $pinduoduo->pre_auth->authorizationRedirect(); 之后再执行的

**Comment by cys138138** [comment]
https://open.pinduoduo.com/#/apidocument/port?id=35

**Comment by cys138138** [comment]
这个接口需要授权的，我修改了一下    public function getTokenFromServer()
    {
        $response = $this->getHttp()->json(self::TOKEN_API, [
            'client_id'     => $this->appId,
            'client_secret' => $this->secret,
            'grant_type'    => 'authorization_code',
            'code'          => $this->code ? $this->code : $_GET['code'],
        ]);
        
        return json_decode(strval($response->getBody()), true);
    }

 $_GET['code'] 这样就正常了

**Comment by justmd5** [comment]
@cys138138 
* 关于code问题我晚点修改下；
* 关于请求接口的问题，我的意思使你请求的那个接口不需要授权，可以直接使用api而不必要使用auth_api ；
* 关于 Foundation sdk，没有文档，自己去研究下源码，源码使最好的文档。
顺便一句，还用记得star下，推给更多人用。😄

**Comment by justmd5** [comment]
@cys138138 fix    https://github.com/justmd5/pinduoduo-sdk/blob/8d0c493954fc7407d4959bc3111cbc060612ce85/src/AccessToken.php#L44 已经优化
