### ISSUE TITLE
code换token的时候报错，以为是我环境的问题，折腾半天没用，最后直接重新安装了一个yii2-basic版本，结果还是一样的错，是有BUG还是我用法不对

### ISSUE THREAD

**Issue by bingying2** [justmd5/pinduoduo-sdk#14]
//错误截图
![微信截图_20201219230426](https://user-images.githubusercontent.com/10571540/102692543-fe85dc80-424e-11eb-9b74-5ffc4ec12fda.png)

//授权之后的回调页面代码，code已经有了，一直报http相关错误，配置文件省略
$pinduoduo = new PinDuoDuo(\Yii::$app->params['pinduoduo']);
$token = $pinduoduo->pre_auth->getAccessToken();
var_dump($token);
return $token;

**Comment by justmd5** [comment]
composer 中添加：hanson/foundation-sdk:^3.0,试试看
