### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Zeemi20** [justmd5/pinduoduo-sdk#16]
Hello, I'm outside china and I can't get the Pinduoduo API, how can I get it?

**Comment by justmd5** [comment]
an then,why you want use the API?

**Comment by Zeemi20** [comment]
I work with freight forwarder and I want to make dropshipping website from pinduoduo, I mean I want to import products from Pinduoduo to my website, but I am not able to get the API, is there any way? I always purchase from Pinduoduo then my agent ship it to me and their services are great so that's why I want to get data from them

**Comment by justmd5** [comment]
I see,but sorry,i have no idea. can not help you!
