### ISSUE TITLE
Cannot call constructor at file:/easyswoole/vendor/justmd5/pinduoduo-sdk/src/Api.php line:25

### ISSUE THREAD

**Issue by LMFName** [justmd5/pinduoduo-sdk#18]
Cannot call constructor at file:/easyswoole/vendor/justmd5/pinduoduo-sdk/src/Api.php line:25

parent::__construct($pinduoduo);

**Comment by justmd5** [comment]
请清理本地缓存包：composer clear   ，本地尝试删除composer.lock ,重新使用最新的版本试试看
