### ISSUE TITLE
签名验证失败

### ISSUE THREAD

**Issue by q764297954** [justmd5/pinduoduo-sdk#19]
array(1) {
  ["error_response"]=>
  array(5) {
    ["error_msg"]=>
    string(18) "签名验证失败"
    ["sub_msg"]=>
    string(18) "签名验证失败"
    ["sub_code"]=>
    string(5) "20004"
    ["error_code"]=>
    int(20004)
    ["request_id"]=>
    string(17) "16176873891122238"
  }
}

**Comment by justmd5** [comment]
请求参数提交一下

**Comment by q764297954** [comment]
这个组件里面有没有上传图片空间的接口设置呢?pdd.goods.filespace.image.upload
接口提交地址变更了 https://gw-upload.pinduoduo.com/api/upload





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月6日(星期二) 晚上6:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [justmd5/pinduoduo-sdk] 签名验证失败 (#19)





 
请求参数提交一下

**Comment by justmd5** [comment]
方便提交示例代码么，我没有对应商家权限，没法调试

**Comment by q764297954** [comment]
好的  稍等下，我改一下看看是否可用  可用的话我把代码邮件发给你 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月8日(星期四) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [justmd5/pinduoduo-sdk] 签名验证失败 (#19)

**Comment by q764297954** [comment]
你好&nbsp; 有没有做过拼多多店铺一键复制或者商品一键复制呢?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月8日(星期四) 下午2:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [justmd5/pinduoduo-sdk] 签名验证失败 (#19)





 
方便提交示例代码么，我没有对应商家权限，没法调试

**Comment by justmd5** [comment]
没有，我没有商家账号

**Comment by q764297954** [comment]
嗯嗯&nbsp; 好吧&nbsp; &nbsp;如果你做到这一块 可以给我分享下代码吗?我也是找朋友借了一个商家号




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月8日(星期四) 下午3:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [justmd5/pinduoduo-sdk] 签名验证失败 (#19)





 
没有，我没有商家账号

**Comment by justmd5** [comment]
> 嗯嗯&nbsp; 好吧&nbsp; &nbsp;如果你做到这一块 可以给我分享下代码吗?我也是找朋友借了一个商家号
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年4月8日(星期四) 下午3:56 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [justmd5/pinduoduo-sdk] 签名验证失败 (#19) 没有，我没有商家账号 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

短期和长期都没有计划做这块

**Comment by q764297954** [comment]
你有qq或微信吗？我加你，有个问题想请教一下 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月12日(星期一) 上午10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [justmd5/pinduoduo-sdk] 签名验证失败 (#19)

**Comment by q764297954** [comment]
商品添加的时候&nbsp; &nbsp;非销售属性添加不上,我想根据我自己的品牌添加,它就提示我品牌不存在



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月12日(星期一) 上午10:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [justmd5/pinduoduo-sdk] 签名验证失败 (#19)





 
Closed #19.
