### ISSUE TITLE
thinkphp5调用出现错误提示

### ISSUE THREAD

**Issue by lifankohome** [justmd5/pinduoduo-sdk#21]
```
        $pinduoduo = new PinDuoDuo($this->config);
        $result = $pinduoduo->auth_api->request('pdd.ddk.oauth.goods.pid.query');
        print_r($result);
```
报错：致命错误: Cannot call constructor(Api.php line 25)

注释掉Api.php的第二十五行parent::__construct($pinduoduo);
报错：Trying to get property of non-object(vendor\hanson\foundation-sdk\src\AbstractAccessToken.php line 221)

请问该怎么处理呢？

**Comment by 923391410** [comment]
这是 **hanson/foundation-sdk** 依赖的问题, 新的4.0.3版本有较大改动, **AbstractAPI** 类将构造函数去除了, 所以导致了这个问题, 解决起来也非常简单, 向 **composer.json** 中的 **require** 对象增加 **"hanson/foundation-sdk": "4.0.2"** 这一行依赖, 将版本控制在4.0.2就可以解决了, 这个版本是还没有删除构造函数的, 所以没有问题

**Comment by 923391410** [comment]
@lifankohome

**Comment by lifankohome** [comment]
嗯嗯，问题解决了，感谢！！
