### ISSUE TITLE
thinkphp5   报错

### ISSUE THREAD

**Issue by guanzhao** [justmd5/pinduoduo-sdk#23]
php 7.2 
foundation-sdk 4.0.2 
pinduoduo-sdk 1.4

AbstractAccessToken.php line 221
Trying to get property 'http' of non-object

**Comment by justmd5** [comment]
1. 删除composer.lock和vendor；
2. 执行：`composer cl`
3. 执行： `composer ins -vvv -o`
4. 如果不行，再来回复

**Comment by guanzhao** [comment]
h

> 1. 删除 composer.lock 和 vendor
> 2. 执行：`composer cl`
> 3. 执行： `composer ins -vvv -o`
> 4. 如果不行，再来回复

还是不行

**Comment by justmd5** [comment]
> h
> 
> > 1. 删除 composer.lock 和 vendor
> > 2. 执行：`composer cl`
> > 3. 执行： `composer ins -vvv -o`
> > 4. 如果不行，再来回复
> 
> 还是不行

再试一下

**Comment by justmd5** [comment]
> h
> 
> > 1. 删除 composer.lock 和 vendor
> > 2. 执行：`composer cl`
> > 3. 执行： `composer ins -vvv -o`
> > 4. 如果不行，再来回复
> 
> 还是不行

最新版本已修复
