### ISSUE TITLE
laravel8.x下安装报错

### ISSUE THREAD

**Issue by Ibazhe** [justmd5/pinduoduo-sdk#24]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - justmd5/pinduoduo-sdk[v1.5.0, ..., v1.5.1] require hanson/foundation-sdk 4.0.2 -> satisfiable by hanson/foundation-sdk[4.0.2].
    - hanson/foundation-sdk 4.0.2 requires guzzlehttp/guzzle ^6.2 -> found guzzlehttp/guzzle[6.2.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - Root composer.json requires justmd5/pinduoduo-sdk ^1.5 -> satisfiable by justmd5/pinduoduo-sdk[v1.5.0, v1.5.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by 1031601644** [comment]
好像是larvael的guzzlehttp依赖是需要大于7.0.1的，但是大佬你的sdk guzzlehttp是大于6.2的，你把composer依赖的guzzlehttp升级到最新英国就好了

**Comment by justmd5** [comment]
修改了下，试试最新的包看，删除原项目的composer.lock 执行下边的命令：

`composer require justmd5/pinduoduo-sdk:dev-master `

如果没问题我打新的tag

**Comment by justmd5** [comment]
> OK了，现在没问题了

好，已经打了新的tag,现在可以直接引入了
```
composer require justmd5/pinduoduo-sdk
```
