### ISSUE TITLE
PHP8 not supported | 不支持PHP8 

### ISSUE THREAD

**Issue by xtrees** [justmd5/pinduoduo-sdk#26]
the package  [hanson/foundation-sdk](https://github.com/Hanson/foundation-sdk)  need to be upgrade to dev-master to support PHP8

需要升级[hanson/foundation-sdk] 才能 支持 PHP8  

我先fork了  

感谢！

**Comment by cys138138** [comment]
您好，你的邮件我已收到！

**Comment by justmd5** [comment]
> the package [hanson/foundation-sdk](https://github.com/Hanson/foundation-sdk) need to be upgrade to dev-master to support PHP8
> 
> 需要升级[hanson/foundation-sdk] 才能 支持 PHP8
> 
> 我先fork了
> 
> 感谢！

刚找foundation-sdk 作者已经发新的了，可以使用了

**Comment by kukudeliu** [comment]
> > the package [hanson/foundation-sdk](https://github.com/Hanson/foundation-sdk) need to be upgrade to dev-master to support PHP8
> > 需要升级[hanson/foundation-sdk] 才能 支持 PHP8
> > 我先fork了
> > 感谢！
> 
> 刚找foundation-sdk 作者已经发新的了，可以使用了

hanson/foundation-sdk 5.0.0 requires php ^7.0 -> your php version (8.0.2) does not satisfy that requirement.
