### ISSUE TITLE
文件上传网关

### ISSUE THREAD

**Issue by gumenghan520** [justmd5/pinduoduo-sdk#27]
文件上传的时候 应该接受什么样的参数  为什么网关总是替换不了  //文件上传兼容
        if (!empty($params['file'])) {
            $method = 'upload';
            array_push($data, [], ['file' => $params['file']]);
            unset($params['file']);
        }  里面的方法也调用了

**Comment by cys138138** [comment]
您好，你的邮件我已收到！

**Comment by justmd5** [comment]
$params['file'] 为你临时文件路径例子：

```php
$result   = $pinduoduo->auth_api->request('pdd.goods.filespace.image.upload',['file'=>'/tmp/1.jpg']);
```
试试看

**Comment by justmd5** [comment]
> 文件上传的时候 应该接受什么样的参数 为什么网关总是替换不了 //文件上传兼容 if (!empty($params['file'])) { $method = 'upload'; array_push($data, [], ['file' => $params['file']]); unset($params['file']); } 里面的方法也调用了

**Comment by gumenghan520** [comment]
> > 文件上传的时候应该接受什么样的参数网关总是为什么替换不能 //文件上传兼容 if (!empty($params['file'])) { $method = 'upload'; array_push($data, [], ['file' => $params['file']]);取消设置($params['文件']); } 里面的方法也调用了
> 
> $params['file'] 为你临时文件路径例子：
> 
> ```
> $result   = $pinduoduo->auth_api->request('pdd.goods.filespace.image.upload',['file'=>'/tmp/1.jpg']);
> ```
> 
> 尝试看看

  $result = $this->GoodsListServices->pinduoduo()->api->request('pdd.ddk.report.img.upload',
            [
                'file' => "/tmp/4579bfa97022ec7e58ed781d62c3c10d.jpg",
            ]);
        return $result;
    我用的这个。不需要授权

**Comment by justmd5** [comment]
> > > 文件上传的时候应该接受什么样的参数网关总是为什么替换不能 //文件上传兼容 if (!empty($params['file'])) { $method = 'upload'; array_push($data, [], ['file' => $params['file']]);取消设置($params['文件']); } 里面的方法也调用了
> > 
> > 
> > $params['file'] 为你临时文件路径例子：
> > ```
> > $result   = $pinduoduo->auth_api->request('pdd.goods.filespace.image.upload',['file'=>'/tmp/1.jpg']);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 尝试看看
> 
> $result = $this->GoodsListServices->pinduoduo()->api->request('pdd.ddk.report.img.upload', [ 'file' => "/tmp/4579bfa97022ec7e58ed781d62c3c10d.jpg", ]); return $result; 我用的这个。不需要授权

理论上是一样的，现在可以了么

**Comment by gumenghan520** [comment]
> > > > 文件上传的时候应该接受什么样的参数网关总是为什么替换不能 //文件上传兼容 if (!empty($params['file'])) { $method = 'upload'; array_push($data, [], ['file' => $params['file']]);取消设置($params['文件']); } 里面的方法也调用了
> > > 
> > > 
> > > $params['file'] 为你临时文件路径例子：
> > > ```
> > > $result   = $pinduoduo->auth_api->request('pdd.goods.filespace.image.upload',['file'=>'/tmp/1.jpg']);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 尝试看看
> > 
> > 
> > $result = $this->GoodsListServices->pinduoduo()->api->request('pdd.ddk.report.img.upload', [ 'file' => "/tmp/4579bfa97022ec7e58ed781d62c3c10d.jpg", ]); return $result; 我用的这个。不需要授权
> 
> 理论上是一样的，现在可以了么

并不行 还是网关错误

**Comment by justmd5** [comment]
> > > > > 文件上传的时候应该接受什么样的参数网关总是为什么替换不能 //文件上传兼容 if (!empty($params['file'])) { $method = 'upload'; array_push($data, [], ['file' => $params['file']]);取消设置($params['文件']); } 里面的方法也调用了
> > > > 
> > > > 
> > > > $params['file'] 为你临时文件路径例子：
> > > > ```
> > > > $result   = $pinduoduo->auth_api->request('pdd.goods.filespace.image.upload',['file'=>'/tmp/1.jpg']);
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 尝试看看
> > > 
> > > 
> > > $result = $this->GoodsListServices->pinduoduo()->api->request('pdd.ddk.report.img.upload', [ 'file' => "/tmp/4579bfa97022ec7e58ed781d62c3c10d.jpg", ]); return $result; 我用的这个。不需要授权
> > 
> > 
> > 理论上是一样的，现在可以了么
> 
> 并不行 还是网关错误

那我今天空闲了试试，先等等吧，还有工作要忙

**Comment by justmd5** [comment]
> > > > > 文件上传的时候应该接受什么样的参数网关总是为什么替换不能 //文件上传兼容 if (!empty($params['file'])) { $method = 'upload'; array_push($data, [], ['file' => $params['file']]);取消设置($params['文件']); } 里面的方法也调用了
> > > > 
> > > > 
> > > > $params['file'] 为你临时文件路径例子：
> > > > ```
> > > > $result   = $pinduoduo->auth_api->request('pdd.goods.filespace.image.upload',['file'=>'/tmp/1.jpg']);
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 尝试看看
> > > 
> > > 
> > > $result = $this->GoodsListServices->pinduoduo()->api->request('pdd.ddk.report.img.upload', [ 'file' => "/tmp/4579bfa97022ec7e58ed781d62c3c10d.jpg", ]); return $result; 我用的这个。不需要授权
> > 
> > 
> > 理论上是一样的，现在可以了么
> 
> 并不行 还是网关错误

```shell 
composer cl
rm -rf vendor
composer require justmd5/pinduoduo-sdk:dev-master 
```
试试看，可以反馈下，我打正式包，我本地测试是可以的

**Comment by gumenghan520** [comment]
> 

"error_msg": "参数错误:file"。。       {
	"name": "4579bfa97022ec7e58ed781d62c3c10d.jpg",
	"type": "image/jpeg",
	"tmp_file": "/tmp/swoole.upfile.vi4kgJ",
	"error": 0,
	"size": 231258
}。    返回参数错误 是我参数传错了吗

**Comment by justmd5** [comment]
> > 
> 
> "error_msg": "参数错误:file"。。 { "name": "4579bfa97022ec7e58ed781d62c3c10d.jpg", "type": "image/jpeg", "tmp_file": "/tmp/swoole.upfile.vi4kgJ", "error": 0, "size": 231258 }。 返回参数错误 是我参数传错了吗

你怎么传的参数，920010043，我qq，加我qq来沟通

**Comment by justmd5** [comment]
fixed #27
