### ISSUE TITLE
文件上传超过1M，CURL错误

### ISSUE THREAD

**Issue by tengteng520** [justmd5/pinduoduo-sdk#28]
您好，问一下 之前的那个文件上传。上传文件大于1M有问题     cURL error 0: The cURL request was retried 3 times and did not succeed. The most likely reason for the failure is that cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong. See https://bugs.php.net/bug.php?id=47204 for more information. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://gw-upload.pinduoduo.com/api/upload。 是我本地配置问题吗？ 详细可以QQ回复我 谢谢

**Comment by cys138138** [comment]
您好，你的邮件我已收到！

**Comment by cys138138** [comment]
您好，你的邮件我已收到！

**Comment by justmd5** [comment]
自己服务器配置问题
